### ISSUE TITLE
新建的项目，安装了babel-plugin-transform-vue-jsx之后，报错

### ISSUE THREAD

**Issue by wqcstrong** [ElementUI/vue-cli-plugin-element#20]
安装了[`babel-plugin-transform-vue-jsx`](https://github.com/vuejs/babel-plugin-transform-vue-jsx)并且按照文档在vue-cli3脚手架新建的项目的`babel.config.js`中修改成如下配置：
```javascript
module.exports = {
  presets: [
    '@vue/app',
    'env'
  ],
  plugins: ["transform-vue-jsx"]
}
```
然后再用`vue add element` 安装 `elementUI`， `babel.config.js`被改成了这样：
```javascript
module.exports = {
  "presets": [
    "@vue/app",
    "env"
  ],
  "plugins": [
    "transform-vue-jsx",
    [
      "component",
      {
        "libraryName": "element-ui",
        "styleLibraryName": "theme-chalk"
      }
    ]
  ]
}


最后，起服务`npm run serve`, 点击查看
![image](https://user-images.githubusercontent.com/23474513/50156800-a851cc00-030a-11e9-9634-e42ed962aaa7.png)

**Comment by wqcstrong** [comment]
错误内容如下：
```javascript
$ npm run serve

> woms@0.1.0 serve D:\woms
> vue-cli-service serve

 INFO  Starting development server...
Starting type checking service...
Using 1 worker with 2048MB memory limit
 94% after seal

 ERROR  Failed to compile with 2 errors                                                                                                                                                                                                               21:05:50

 error  in ./src/views/Home.vue?vue&type=script&lang=ts&

Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'bindings' of null
    at Scope.moveBindingTo (D:\woms\node_modules\@babel\traverse\lib\scope\index.js:867:13)
    at BlockScoping.updateScopeInfo (D:\woms\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:364:17)
    at BlockScoping.run (D:\woms\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:330:12)
    at PluginPass.BlockStatementSwitchStatementProgram (D:\woms\node_modules\babel-plugin-transform-es2015-block-scoping\lib\index.js:70:24)
    at newFn (D:\woms\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\woms\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\woms\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\woms\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\woms\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\woms\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\woms\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\woms\node_modules\@babel\traverse\lib\index.js:94:17)
    at traverse (D:\woms\node_modules\@babel\traverse\lib\index.js:76:12)
    at transformFile (D:\woms\node_modules\@babel\core\lib\transformation\index.js:88:29)
    at runSync (D:\woms\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at runAsync (D:\woms\node_modules\@babel\core\lib\transformation\index.js:35:14)

 @ ./src/views/Home.vue?vue&type=script&lang=ts& 1:0-322 1:338-341 1:343-662 1:343-662
 @ ./src/views/Home.vue
 @ ./src/router.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://192.168.3.102:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.ts
```

**Comment by wqcstrong** [comment]
`@babel/preset-env` is in `@vue/babel-preset-app's` features.
