### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by vsantw** [ElementUI/vue-cli-plugin-element#58]
Vue.use(Element) ???
vue3好像不能这样弄吧, 
vue create my-app
cd my-app
vue add element
然后 npm run serve 
进入网站显示空白并且控制台报错
现在是不支持vue3.2吗？

**Comment by AdrianRonaldo10** [comment]
同样的错误（OVO）

**Comment by AdrianRonaldo10** [comment]
我是8080的
Uncaught runtime errors:
Cannot read properties of undefined (reading 'prototype')
TypeError: Cannot read properties of undefined (reading 'prototype')
    at eval (webpack-internal:///./node_modules/element-ui/lib/utils/types.js:41:115)
    at ./node_modules/element-ui/lib/utils/types.js (http://localhost:8080/js/chunk-vendors.js:845:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:277:33)
    at fn (http://localhost:8080/js/app.js:527:21)
    at eval (webpack-internal:///./node_modules/element-ui/lib/utils/util.js:18:14)
    at ./node_modules/element-ui/lib/utils/util.js (http://localhost:8080/js/chunk-vendors.js:856:1)
    at __webpack_require__ (http://localhost:8080/js/app.js:277:33)
    at fn (http://localhost:8080/js/app.js:527:21)
    at eval (webpack-internal:///./node_modules/element-ui/lib/locale/format.js:43:13)
    at ./node_modules/element-ui/lib/locale/format.js (http://localhost:8080/js/chunk-vendors.js:501:1)
